name: scrumflow
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dio: ^5.6.0                           #https://pub.dev/packages/dio/install
  easy_sidemenu: ^0.6.0
  form_builder_validators: ^11.0.0
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.10+1                #https://pub.dev/packages/flutter_svg/install
  get: ^4.6.5
  http: ^1.2.2                          #https://pub.dev/packages/http/install
  intl: ^0.19.0                         #https://pub.dev/packages/intl/install
  mask_text_input_formatter: ^2.9.0
  multi_select_flutter: ^4.1.3          #https://pub.dev/packages/multi_select_flutter
  shared_preferences: ^2.3.2            #https://pub.dev/packages/shared_preferences/install
  shimmer: ^3.0.0                       #https://pub.dev/packages/shimmer

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_launcher_icons:
    android: "ic_launcher"
    ios: true
    image_path: "assets/images/logo.png"
    web:
      generate: true
      image_path: "assets/images/logo.png"

flutter:

  uses-material-design: true

  assets:
      - assets/images/
      - assets/icons/
      - .env

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
